### ISSUE TITLE
Tracking SharedArrayBuffer status

### ISSUE THREAD

**Issue by mulderr** [WebGHC/webabi#4]
Due to Meltdown/Spectre all major browser vendors are temporarily disabling `SharedArrayBuffer` by default.

* [Chrome](https://www.chromium.org/Home/chromium-security/ssca)
* [Firefox](https://blog.mozilla.org/security/2018/01/03/mitigations-landing-new-class-timing-attack/)
* [Edge](https://blogs.windows.com/msedgedev/2018/01/03/speculative-execution-mitigations-microsoft-edge-internet-explorer/)

Importantly:
> This is a temporary measure until other mitigations are in place.

Until then this breaks `nanosleep` which is using SAB explicitly.

**Comment by mulderr** [comment]
According to the information [here](https://www.chromium.org/Home/chromium-security/ssca):
> SharedArrayBuffer will be re-enabled in Chrome versions where Site Isolation is on by default.

Chrome 67 seems to have site isolation on by default and link below suggests Chrome 68 re-enables SAB. (yay!)

Some comments [here](https://github.com/tc39/security/issues/3) suggest Firefox does not have a plan yet but they are discussing it. Until then SAB has to be enabled manually.

Edge... do we care?

**Comment by mulderr** [comment]
Closing. Firefox may still take a while but new versions of Chrome should work out of the box so there's an easy solution to point people to.

**Comment by ElvishJerricco** [comment]
Great news. I'm pretty hopeful that this will be on by default in every major browser within the year, so I don't mind closing this.
